title: Anna Williams
email: hello (at) anna-maths (dot) xyz
github_username:  awsloth

baseurl: ""
url: "https://anna-maths.xyz"

plugins:
  - jekyll-feed

markdown: kramdown
highligher : rouge

exclude:
    - "*.agdai"
