title: Anna Williams
email: hello (at) anna-maths (dot) xyz
github_username:  awsloth

baseurl: ""
url: "https://anna-maths.xyz"

markdown: kramdown
highligher : rouge

exclude:
    - "*.agdai"

plugins:
  - jekyll-regex-replace
