name: CI

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
        python-version: '3.x'
     - name: Install dependencies
       run: python -m pip install markdown2
     - uses: actions/checkout@v3
     - run: python compile.py
     - run: find . -not -path "./.git/*" -not -name ".git" -not -path "./_site/*" -not -name "_site" -delete
     - run: "mv _site/* _site/.* . || :"
     - run: git config --global user.email "noreply@github.com"
     - run: git config --global user.name "GitHub"
     - run: git checkout -b dist
     - run: git add .
     - run: git commit -m "Update build"
     - run: git rebase --root
     - run: git push origin dist --force
